/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.16
 * Generated at: 2023-11-18 16:22:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.Statement;
import db.ConexionDB;

public final class inicio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("db.ConexionDB");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Inicio</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/inteBoot.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");

	String id=request.getParameter("id");
	String na=new String();
	String foto=new String();
	if(id!=null) {
		ConexionDB conex=new ConexionDB();
		Statement st=conex.conectar();
		ResultSet rs=st.executeQuery("SELECT * FROM usuarios WHERE id="+id);
		rs.next();
		na=rs.getString("nombre") + " "+ rs.getString("apellido");
		foto=rs.getString("fotoPerfil");
	}		
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- menu -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-body-tertiary\" data-bs-theme=\"dark\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <a class=\"navbar-brand d-none d-sm-block\" href=\"#\">\r\n");
      out.write("                <img src=\"images/codoacodo.png\" alt=\"codo\" class=\"w-25\" >\r\n");
      out.write("                Conf BsAs\r\n");
      out.write("            </a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarText\"\r\n");
      out.write("                aria-controls=\"navbarText\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarText\">\r\n");
      out.write("                <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                   \r\n");
      out.write("                </ul>\r\n");
      out.write("                <span class=\"navbar-text\">\r\n");
      out.write("                    <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                        <span>");
 out.print(na); 
      out.write("</span>\r\n");
      out.write("                            <img alt=\"\" src=\"");
 out.print(foto); 
      out.write("\" class=\"img-fluid rounded-4 \" width=\"40px\">\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">La Conferencia</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"#\">Oradores</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link text-success\" href=\"ticket/comprarTicket.html\">Comprar Tickets</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- carrusel -->\r\n");
      out.write("    <div>\r\n");
      out.write("        <div id=\"carouselExampleCaptions\" class=\"carousel slide\">\r\n");
      out.write("            <div class=\"carousel-indicators\">\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"0\" class=\"active\"\r\n");
      out.write("                    aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"1\"\r\n");
      out.write("                    aria-label=\"Slide 2\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"2\"\r\n");
      out.write("                    aria-label=\"Slide 3\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <img src=\"images/ba1.jpg\" class=\"d-block w-100 brilloOscuro\" alt=\"b\">\r\n");
      out.write("                    <div class=\"carousel-caption d-block\">\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <div class=\"col-0 col-lg-4\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-lg-8  text-center text-lg-end \">\r\n");
      out.write("                                <h5 class=\"fs-3\">Conf Bs As</h5>\r\n");
      out.write("                                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere asperiores, eveniet inventore nobis\r\n");
      out.write("                                    pariatur quas, labore ut expedita repellendus itaque cumque odio distinctio maxime ipsam eum dolorum\r\n");
      out.write("                                    reprehenderit ratione unde.</p>\r\n");
      out.write("                                <div class=\"mb-4 d-none d-md-block\">\r\n");
      out.write("                                    <a href=\"\" class=\"btn btn-outline-light\">Quiero ser orador</a>\r\n");
      out.write("                                    <a href=\"\" class=\"btn btn-success\">Comprar Ticket</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("        \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img src=\"images/ba2.jpg\" class=\"d-block w-100 brilloOscuro\" alt=\"a\">\r\n");
      out.write("                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                        <h5>Second slide label</h5>\r\n");
      out.write("                        <p>Some representative placeholder content for the second slide.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img src=\"images/ba3.jpg\" class=\"d-block w-100 brilloOscuro\" alt=\"c\">\r\n");
      out.write("                    <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                        <h5>Third slide label</h5>\r\n");
      out.write("                        <p>Some representative placeholder content for the third slide.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- oradores -->\r\n");
      out.write("    <div class=\"text-center m-1\">\r\n");
      out.write("        <div class=\"textoChico mt-3\">\r\n");
      out.write("            CONOCE A LOS \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fs-5\">\r\n");
      out.write("            ORADORES\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex justify-content-center flex-wrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- orador -->\r\n");
      out.write("        <div class=\"card mx-1 mb-3\" style=\"width: 18rem;\">\r\n");
      out.write("            <img src=\"images/seteve.png\" class=\"card-img-top\" alt=\"steve\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"botones mb-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm btn-warning\">Javascript</a>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm btn-info text-light\">React</a>\r\n");
      out.write("        \r\n");
      out.write("                </div>\r\n");
      out.write("                <h5 class=\"card-title\">Steve Jobs</h5>\r\n");
      out.write("                <p class=\"card-text\">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit illum laboriosam quaerat                quod ab nobis, corporis aut iusto debitis blanditiis tempora fugiat quae, nihil doloremque sed corrupti                eaque adipisci possimus.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- orador -->\r\n");
      out.write("        <div class=\"card mx-1 mb-3\" style=\"width: 18rem;\">\r\n");
      out.write("            <img src=\"images/bill.png\" class=\"card-img-top\" alt=\"steve\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"botones mb-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm btn-warning\">Javascript</a>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm btn-info text-light\">React</a>\r\n");
      out.write("        \r\n");
      out.write("                </div>\r\n");
      out.write("                <h5 class=\"card-title\">Bill Gates</h5>\r\n");
      out.write("                <p class=\"card-text\">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit illum laboriosam quaerat                quod ab nobis, corporis aut iusto debitis blanditiis tempora fugiat quae, nihil doloremque sed corrupti                eaque adipisci possimus.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- orador -->\r\n");
      out.write("        <div class=\"card mx-1 mb-3\" style=\"width: 18rem;\">\r\n");
      out.write("            <img src=\"images/adda.png\" class=\"card-img-top\" alt=\"steve\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"botones mb-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm btn-warning\">Javascript</a>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm btn-info text-light\">React</a>\r\n");
      out.write("        \r\n");
      out.write("                </div>\r\n");
      out.write("                <h5 class=\"card-title\">Adda Lovelace</h5>\r\n");
      out.write("                <p class=\"card-text\">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit illum laboriosam quaerat                quod ab nobis, corporis aut iusto debitis blanditiis tempora fugiat quae, nihil doloremque sed corrupti                eaque adipisci possimus.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>    \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row \">\r\n");
      out.write("            <div class=\"col-lg p-0\">\r\n");
      out.write("                <img src=\"images/honolulu.jpg\" alt=\"honolulu\" class=\"img-fluid\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg bgGrisOscuro text-white\">\r\n");
      out.write("                <div class=\"fs-4 mt-1 mb-3 mt-4\">\r\n");
      out.write("                    BsAs - Octubre\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eligendi eos voluptates quo esse consectetur aut, cupiditate voluptas laborum. Animi a architecto unde, commodi itaque enim asperiores iste consequuntur excepturi vel.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-outline-light\">ConocÃ© mÃ¡s</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- formulario orador -->\r\n");
      out.write("    <div class=\"container text-center\">\r\n");
      out.write("        <div class=\"mb-1 mt-3\">\r\n");
      out.write("            CONVIÃRTETE EN UN\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fs-2 mb-3\">\r\n");
      out.write("            ORADOR\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"server/procesarCompTicket.html\" method=\"post\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md mb-3\">\r\n");
      out.write("                    <input type=\"text\" name=\"nombre\" id=\"nombre\" placeholder=\"Nombre\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md mb-3\">\r\n");
      out.write("                    <input type=\"text\" name=\"apellido\" id=\"apellido\" placeholder=\"apellido\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col mb-3\">\r\n");
      out.write("                    <textarea name=\"\" id=\"\" rows=\"5\" class=\"form-control\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-3\">\r\n");
      out.write("                <input type=\"submit\" value=\"Enviar\" class=\"btn btn-primary\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("    <div class=\"bg-dark text-light\" style=\"height: 50px;\">\r\n");
      out.write("        <div class=\"d-flex justify-content-around align-items-center \">\r\n");
      out.write("            <a href=\"\" class=\"text-decoration-none text-light\">link 1</a>\r\n");
      out.write("            <a href=\"\" class=\"text-decoration-none text-light\">link 2</a>\r\n");
      out.write("            <a href=\"\" class=\"text-decoration-none text-light\">link 3</a>\r\n");
      out.write("            <a href=\"\" class=\"text-decoration-none text-light\">link 4</a>\r\n");
      out.write("            <a href=\"\" class=\"text-decoration-none text-light\">link 5</a>\r\n");
      out.write("            <a href=\"\" class=\"text-decoration-none text-light\">link 6</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
