/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.16
 * Generated at: 2023-11-20 14:26:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class iniciarSesion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!doctype html>\r\n");
      out.write("\r\n");
      out.write("    <html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"icon\" href=\"../images/Logo Regal 1.png\" type=\"image/png\">\r\n");
      out.write("\r\n");
      out.write("        <title>Iniciar Sesiï¿½n - Regalerï¿½a</title>\r\n");
      out.write("        <!-- Boostrap-->\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("            integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\r\n");
      out.write("        <!-- Css-->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("        <!-- Fuentes -->\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <!--INICIO NAV-->\r\n");
      out.write("        <div class=\"row mt-5 cortes\">\r\n");
      out.write("            <div class=\"fuente fs-6 text-center m-1 text-white\">\r\n");
      out.write("                Grupo: Regaleria - 2023. Integrantes: Tammy, Vazques - Esteban, Carmona - Evans, Ricardo - Walter,\r\n");
      out.write("                Catellan\r\n");
      out.write("                - Chico, Rodrigo.\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light fuente\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("                <img src=\"../images/logo.png\" width=\"100\" height=\"100\" alt=\"Logo\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"search-container\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control form-control-sm mt-4\" placeholder=\"Buscar productos\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"container-fluid bg-dark-subtle text-center fuente fs-6 \">\r\n");
      out.write("            <div class=\"row align-items-center justify-content-center links-nav ancho-nav\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">PRODUCTOS</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">Cï¿½MO COMPRAR</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">QUIï¿½NES SOMOS</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">CONTACTO</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- FIN NAV-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- INICIO FORMULARIO SECION-->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container fuente\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <h2 class=\"fuente fs-4 text-center m-4\">Login administrador</h2>\r\n");
      out.write("                <div class=\"col-sm-6 offset-sm-3\">\r\n");
      out.write("\r\n");
      out.write("                    <form class=\"mt-3\" action=\"../controller/checkLogin.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"exampleInputEmail1\" class=\"form-label fs-6\">Direcciï¿½n de correo</label>\r\n");
      out.write("                            <input type=\"email\" name=\"user\" class=\"form-control\" placeholder=\"Ej.: tunombre@email.com\"\r\n");
      out.write("                                id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"exampleInputPassword1\" class=\"form-label fs-6\">Contraseï¿½a</label>\r\n");
      out.write("                            <input type=\"password\" name=\"pass\" class=\"form-control\" id=\"exampleInputPassword1\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"mb-3 form-check\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"form-check-input fs-6\" id=\"exampleCheck1\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"exampleCheck1\">Mostrar contraseï¿½a</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn button boton-ingresar\">Ingresar</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- FIN FORMULARIO-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- INICIO FOOTER-->\r\n");
      out.write("        <footer class=\"footer m-3 \">\r\n");
      out.write("            <div class=\"footer\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"row \">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-4\">\r\n");
      out.write("                            <h4 class=\"footer-title font-body text-uppercase fuente fs-6 text-center\">Navegaciï¿½n</h4>\r\n");
      out.write("                            <ul class=\"text-center\">\r\n");
      out.write("                                <li class=\"list-unstyled\">\r\n");
      out.write("                                    <a class=\"text-decoration-none text-dark\" href=\"#\">SET DE MATES</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-unstyled\">\r\n");
      out.write("                                    <a class=\"text-decoration-none text-dark\" href=\"#\">RELOJERIA</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-unstyled\">\r\n");
      out.write("                                    <a class=\"text-decoration-none text-dark\" href=\"#\">CARTERAS</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-4\">\r\n");
      out.write("                            <h4 class=\"footer-title font-body text-uppercase fuente fs-6 text-center\">Medios de pago\r\n");
      out.write("                            </h4>\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/visa@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"visa\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/mastercard@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"mastercard\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/amex@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"amex\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/diners@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"diners\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/ar/banelco@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"ar_banelco\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/ar/cabal@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"ar_cabal\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/ar/tarjeta-naranja@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"ar_tarjeta-naranja\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/ar/tarjeta-shopping@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"ar_tarjeta-shopping\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/mercadopago@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"mercadopago\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/ar/argencard@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"ar_argencard\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/pagofacil@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"pagofacil\">\r\n");
      out.write("                            <img src=\"//d26lpennugtm8s.cloudfront.net/assets/common/img/logos/payment/new_logos_payment/rapipago@2x.png\"\r\n");
      out.write("                                class=\"footer-payship-img\" width=\"50\" alt=\"rapipago\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-4\">\r\n");
      out.write("                            <h4 class=\"footer-title font-body text-uppercase fuente fs-6 text-center\">Contactanos</h4>\r\n");
      out.write("                            <ul class=\"text-center\">\r\n");
      out.write("                                <li class=\"list-unstyled\"> +54 9 (numero de telefono)</li>\r\n");
      out.write("                                <li class=\"list-unstyled\">Tp-integradorRegaleria@email.com</li>\r\n");
      out.write("                                <li class=\"list-unstyled\">Direccion y dias de trabajo</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row mt-5 cortes\">\r\n");
      out.write("                        <div class=\"footer-legal font-small-extra text-center m-3\">\r\n");
      out.write("                            <img src=\"../images/copyright.png\" width=\"25\" alt=\"copy\">\r\n");
      out.write("                            Copyright Tp-Integrador Regaleria - 2023. Todos los derechos reservados.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- FIN FOOTER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("            integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("            crossorigin=\"anonymous\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
